### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by EmrysMyrddin** [cozy/create-cozy-app#1299]
After creating an app with `yarn create cozy-app cozy-ocr`, i'm getting a webpack error at app start.

```bash
➜  cozy-ocr yarn start
yarn run v1.21.1
$ cs start --hot --browser
Compiling for development environment and browser target...
                                                                                                    95% emitting✖ ｢wdm｣: TypeError: Cannot read property 'tapAsync' of undefined
    at /Users/valentin/Dev/Projects/cozy-ocr/node_modules/webpack-dev-middleware/lib/fs.js:22:37
    at _next4 (eval at create (/Users/valentin/Dev/Projects/cozy-ocr/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/valentin/Dev/Projects/cozy-ocr/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/valentin/Dev/Projects/cozy-ocr/node_modules/copy-webpack-plugin/dist/index.js:90:9
```

It is probably a dependency version problem in the webpack plugins used by your scripts.

**Comment by EmrysMyrddin** [comment]
There is also lots of unmet dependencies at install. Probably not a good thing :-)

```bash
warning "cozy-bar > cozy-ui@21.4.1" has unmet peer dependency "@material-ui/core@3.9.3".
warning "cozy-bar > cozy-ui@21.4.1" has incorrect peer dependency "piwik-react-router@^0.8.2".
warning "cozy-bar > cozy-ui@21.4.1" has unmet peer dependency "preact@^8.3.1".
warning "cozy-bar > cozy-ui@21.4.1" has unmet peer dependency "preact-portal@^1.1.3".
warning "cozy-bar > piwik-react-router@0.12.1" has unmet peer dependency "history@^3.0.0 || ^4.0.0".
warning "cozy-ui > react-hot-loader@4.12.19" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning "cozy-bar > cozy-ui > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
warning "cozy-bar > cozy-ui > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
warning " > cozy-ui@21.7.0" has unmet peer dependency "@material-ui/core@3.9.3".
warning " > cozy-ui@21.7.0" has unmet peer dependency "cozy-device-helper@1.7.2".
warning " > cozy-ui@21.7.0" has unmet peer dependency "piwik-react-router@^0.8.2".
warning " > cozy-ui@21.7.0" has unmet peer dependency "preact@^8.3.1".
warning " > cozy-ui@21.7.0" has unmet peer dependency "preact-portal@^1.1.3".
warning "cozy-scripts > vue-jest@3.0.4" has unmet peer dependency "vue@^2.x".
warning "cozy-scripts > vue-jest@3.0.4" has unmet peer dependency "vue-template-compiler@^2.x".
warning " > eslint-plugin-prettier@3.1.0" has unmet peer dependency "eslint@>= 5.0.0".
warning " > eslint-plugin-react@7.14.2" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
```

**Comment by Crash--** [comment]
Hi EmrysMyrddin, 

Thanks for taking the time to create an issue. We have an issue about the webpack issue : https://github.com/cozy/create-cozy-app/issues/1289 . We didn't fix it yet since we don't use the latest version internally. So, if you want to take a look, don't hesitate ;). Otherwise, let's see if we can do something in the next few days.

**Comment by Crash--** [comment]
Hi @EmrysMyrddin, 

We have unpublished the version we didn't use internally. Using the latest version should be ok. 

I'm closing the issue for now.
