### ISSUE TITLE
yarn create cozy-app fails with node 12

### ISSUE THREAD

**Issue by Gaadek** [cozy/create-cozy-app#1323]
Hi,

I'm trying to setup a dev environment for Cozy.
For informtion, my local env is the following:
- I'm running Ubuntu 18.04
- Version of Yarn is: 1.22.4
- Version of node is: 12.16.1
- I run a Cozy development image in docker (following these instructions: https://docs.cozy.io/en/tutorials/app/)

When I run the `yarn create cozy-app mycosyapp` comande, I get the following error message:
```
ERROR:
(node:24578) UnhandledPromiseRejectionWarning: #<Object>
(node:24578) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24578) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The failure comes from the build operation and the **--verbose** option provides more details:
```
/home/gaadek/.cache/node-gyp/12.16.1/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
leveldown.target.mk:129: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: Leaving directory '/home/gaadek/projects/mycozyapp/node_modules/leveldown/build'
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gaadek/projects/mycozyapp/node_modules/leveldown
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

This makes me feel the create-cozy-app does not support Node12 (yet), can you confirm this?

**Comment by Gaadek** [comment]
Hi,

Using `nvm`, I've been able to run the `yarn create cozy-app mycosyapp` with node 10.20.0 successfully! 

So the current create-cozy-app is not compatible with Node 12.16.1

**Comment by Crash--** [comment]
Hello @Gaadek 

Thanks for you report. We mainly still use node 10 internally to build our app. 

So I can confirm that we don't test if on node 12. Let's see what we can do in the future for that
